// Reelhouse application configuration.
// The TMDB Read Access Token is supplied by the project owner as the default application credential.
export const TMDB_READ_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlMzlkMDkyODJmZDczNzkyYjFlODExMGM0ODYxZWU3ZiIsIm5iZiI6MTc3MjUzMDEwMi4zMzQsInN1YiI6IjY5YTZhOWI2ZDEzMmNjNDljNDc0M2NkNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WZUJBxPNla8A0xn9kuJCAm8INNOWn1BxQnS5TWeeqEc";
